# Generated by Django 5.1.1 on 2024-10-13 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='user',
            new_name='consumer',
        ),
        migrations.AddField(
            model_name='project',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='project',
            name='ratings',
            field=models.ManyToManyField(blank=True, related_name='projects', to='project.rating'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_ratings', to='project.project'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('project', 'consumer')},
        ),
    ]
